### ISSUE TITLE
/Users/isaac_000/... not found

### ISSUE THREAD

**Issue by icook** [simplecrypto/ppagent#6]
Looks like PyInstaller has forgotten to bundle some dependency and needs to have it declared explicitly.

**Comment by raid5** [comment]
Attached screenshot of crash.

![ppagent-crash](https://f.cloud.github.com/assets/15592/2415729/0e7baccc-aaf9-11e3-92b0-d916fb6992af.jpg)

**Comment by icook** [comment]
Thanks, helps a lot.
